[project]
authors = ["Nicklas <gitnicklas@pm.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "AudioViz"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
librosa = ">=0.10.2.post1,<0.11"
matplotlib = ">=3.10.0,<4"
numpy = ">=2.0.2,<3"
python-sounddevice = "*"
pyqtgraph = ">=0.13.7,<0.14"
pyqt = "*"
loguru = ">=0.7.2,<0.8"
pyopengl = ">=3.1.9,<4"
snakeviz = ">=2.2.2,<3"
cupy = ">=13.4.1,<14"
pdoc = ">=14.4.0,<15"


[pypi-dependencies]
audioviz = { path = ".", editable = true }
