[project]
authors = ["Nicklas <gitnicklas@pm.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "AudioViz"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
librosa = "*"
matplotlib = "*"
numpy = "*"
python-sounddevice = "*"
pyqtgraph = "*"
pyqt = "*"
loguru = "*"
pyopengl = "*"
snakeviz = "*"
cupy = "*"
pdoc = "*"
opencv = "*"
qdarkstyle = "*"
python = "3.11.*"
h5py = ">=3.14.0,<4"
imageio = ">=2.37.0,<3"
pysoundfile = ">=0.13.1,<0.14"


[pypi-dependencies]
audioviz = { path = ".", editable = true }
mediapipe = ">=0.10.14, <0.11"
# mediapipe = { }
