[project]
authors = ["Nicklas <gitnicklas@pm.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "AudioViz"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
librosa = "*"
matplotlib = "*"
numpy = "*"
python-sounddevice = "*"
pyqtgraph = "*"
pyqt = "*"
loguru = "*"
pyopengl = "*"
snakeviz = "*"
pdoc = "*"
opencv = "*"
qdarkstyle = "*"
python = "3.12.*"
debugpy = ">=1.8.15,<2"

# Platform-specific dependencies
[target.linux-64.dependencies]
cupy = "*"

[target.osx-arm64.dependencies]
# no cupy on macOS

[pypi-dependencies]
audioviz = { path = ".", editable = true }
mediapipe = ">=0.10.14, <0.11"
